language: generic
sudo: required
services:
  - dockerfile

before_install:
  - docker build -t mnochuba/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mnochuba/docker-react npm run test